#!/usr/bin/env bash
# configure new ubuntu machine
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" >/tmp/tes
sudo sed -i 's-root \(.*\);-root /tmp;-' /etc/nginx/sites-enabled/default
sudo sed -i 's/index /index tes /' /etc/nginx/sites-enabled/default
sudo sed -i 's|server_name _;|server_name _;\n\nlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}|' /etc/nginx/sites-enabled/default
sudo service nginx restart

