#!/usr/bin/env bash
# configure new ubuntu machine
sudo apt-get update
sudo apt-get install nginx -y
sudo echo "Hello World!" >/tmp/tes
sudo echo "Ceci n'est pas une page" >/tmp/error404.html
sudo sed -i 's-root \(.*\);-root /tmp;-' /etc/nginx/sites-available/default
sudo sed -i 's/index /index tes /' /etc/nginx/sites-available/default
sudo sed -i 's|server_name _;|server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}|' /etc/nginx/sites-available/default
sudo sed -i 's|^[^#]location / {|\tlocation / {\n\t\terror_page 404 /error404.html;|' /etc/nginx/sites-available/default
sudo service nginx restart
