#!/usr/bin/env bash
# This script adds a header X-Served-By
host=$(hostname)
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" >/tmp/tes
echo -e "Ceci n'est pas une page\n" >/tmp/error404.html
sudo sed -i 's-root .*;-root /tmp;-' /etc/nginx/sites-available/default
sudo sed -i 's/index /index tes /' /etc/nginx/sites-available/default
sudo sed -i 's|server_name _;|server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}|' /etc/nginx/sites-available/default
sudo sed -i 's|^[^#]location / {|\tlocation / {\n\t\terror_page 404 /error404.html;|' /etc/nginx/sites-available/default
sudo sed -i "s/^server {/server {\n\tadd_header X-Served-By $host;\n/" /etc/nginx/sites-available/default
sudo service nginx restart
