#!/usr/bin/env bash
#install HAproxy load balancer
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get install haproxy=2.0.\* -y
mv /etc/haproxy/haproxy.cfg{,.original}

printf %s "bvackend web-backend
   balance roundrobin
   server 58119-web-01 34.207.154.247:80 check
   server 58119-web-02 100.25.3.135:80 check
   " >> /etc/haproxy/haproxy.xfg
