#!/usr/bin/env bash
#process and PID file
sudo touch /var/run/myscript.pid
sudo chmod 747 /var/run/myscript.pid
echo "$$" | sudo tee /var/run/myscript.pid
while true
do
trap "echo I hate the kill command; sudo rm /var/run/myscript.pid; exit 0" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "sudo rm /var/run/myscript.pid; exit 0" SIGQUIT
echo "To infinity and beyond"
done
