#!/usr/bin/env bash
# this script tells the story of passwd file
while IFS=: read -r user pw uid gid info hd cs
do
echo "the user $user is part of the $gid gang, lives in $hd and rides $cs. $uid's place is protected by the passcode $pw, more info about the user here: $info"
done < "/etc/passwd"
