#!/usr/bin/env bash
# this script will display the hour and minute of 12hr and 59min
hour="0"
while [ $hour -le 12 ]
do
echo "Hour: $hour"
min="1"
while [ $min -le 59 ]
do
echo "$min"
min=$((min+1))
done
hour=$((hour+1))
done
