#!/usr/bin/env bash
# change the localhost and facebook.com IP resolves
sudo cp /etc/hosts ~/hosts.new
sudo sed -i 's-127.0.0.1\(.*\)-127.0.0.2	localhost-' ~/hosts.new
sudo sed -i 's-157.240.11.35\(.*\)-8.8.8.8	facebook.com-' ~/hosts.new
sudo sed -i 's-\(.*\)localhost-127.0.0.2	localhost-' ~/hosts.new
sudo sed -i 's-\(.*\)facebook.com-8.8.8.8	facebook.com-' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
