#!/usr/bin/env bash
# run nginx as nginx user
sudo sed -i "s/#user.*/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo sed -i 's/default_server\(.*\);/default_server;/' /etc/nginx/sites-available/default
sudo chmod o+r /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
