#!/usr/bin/env bash
# run nginx as nginx user
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo sed -i 's/default_server ipv6only=on;/default_server;/' /etc/nginx/sites-available/default
sudo chmod o+r /etc/nginx/nginx.conf
sudo pkill -f apache2
sudo -u nginx service nginx restart
